<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

class Fontis_Blog_Block_Form_Image extends Varien_Data_Form_Element_Image
{
    /**
     * Replaces the image file path that is automatically generated by Magento with the one determined
     * by the relevant blog model's file path constant.
     *
     * For example:
     *  [Before] - .../media/image01.png
     *  [After] - .../media/fontis_blog/cat/image01.png
     *
     * This is mostly for presentational purposes.
     *
     * @return string
     */
    public function getElementHtml()
    {
        $html = parent::getElementHtml();
        if ($registry = Mage::registry("blog_data")) {
            $html = $this->fixImageUrls($registry, $html);
        }
        return $html;
    }

    /**
     * @param Varien_Object $registry
     * @param string $html
     * @return string
     */
    protected function fixImageUrls(Varien_Object $registry, $html)
    {
        $replace = null;
        $mediaBaseUrl = Mage::getBaseUrl("media");

        if ($registry instanceof Fontis_Blog_Model_Post) {
            $replace = $mediaBaseUrl . $registry->getImageBasePath() . "/";
        } elseif ($registry instanceof Fontis_Blog_Model_Blog) {
            $replace = $mediaBaseUrl . Fontis_Blog_Helper_Data::BLOG_MEDIA_TOPLEVEL . "/" . Fontis_Blog_Helper_Data::BLOG_MEDIA_MAIN . "/";
        } elseif ($registry instanceof Fontis_Blog_Model_Cat) {
            $replace = $mediaBaseUrl . Fontis_Blog_Model_Cat::CAT_IMAGE_BASEPATH;
        }

        if ($replace !== null) {
            $html = str_replace($mediaBaseUrl, $replace, $html);
        }

        return $html;
    }
}
