<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php /** @var $this Fontis_Blog_Block_Author_List */ ?>

<div class="page-title">
    <h1><?php echo $this->getBlog()->getAuthorLabel(); ?></h1>
</div>

<ul>
<?php foreach ($this->getAuthors() as $author): ?>
    <li>
        <a href="<?php echo $author->getAuthorUrl(); ?>"><?php echo $author->getName(); ?></a>
    </li>
<?php endforeach; ?>
</ul>
