<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php /** @var Fontis_Blog_Block_Menu $this */ ?>

<div class="block block-list block-blog">
    <div class="block-title">
        <h4><?php echo $this->getBlog()->getTitle(); ?></h4>
    </div>
    <div class="block-content">
        <?php echo $this->getChildHtml("archives"); ?>
        <?php if ($posts = $this->getRecent()): ?>
        <h5><?php echo $this->getBlogHelper()->__("Recent Posts"); ?></h5>
        <ul>
            <?php foreach ($posts as $post): ?>
                <li>
                    <a href="<?php echo $post->getPostUrl(); ?>"><?php echo $post->getTitle(); ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <h5><?php echo $this->getBlogHelper()->__("Categories"); ?></h5>
        <ul>
            <?php $cats = $this->getCategories(); ?>
            <?php foreach ($cats as $cat): ?>
                <li>
                    <a href="<?php echo $cat->getCatUrl(); ?>"><?php echo $cat->getTitle(); ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php echo $this->getChildHtml("tags"); ?>
    </div>
</div>
