<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php /** @var $this Fontis_Blog_Block_Pager_Blog */ ?>

<?php if ($newerPostsUrl = $this->getNewerPostsUrl()): ?>
<div class="left">
<a href="<?php echo $newerPostsUrl; ?>"><?php echo Mage::helper("blog")->__("Newer Posts"); ?></a>
</div>
<?php endif; ?>
<?php if ($olderPostsUrl = $this->getOlderPostsUrl()): ?>
<div class="right">
    <a href="<?php echo $olderPostsUrl; ?>"><?php echo Mage::helper("blog")->__("Older Posts"); ?></a>
</div>
<?php endif; ?>
