<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php /** @var $this Fontis_Blog_Block_Post */ ?>

<?php
/** @var $helper Fontis_Blog_Helper_Data */
$helper = Mage::helper("blog");
$blog = $this->getBlog();
$post = $this->getPost();
/** @var $customerHelper Mage_Customer_Helper_Data */
$customerHelper = Mage::helper("customer");
?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml(); ?></div>
<div class="postWrapper" itemprop="blogPost" itemscope itemtype="http://schema.org/BlogPosting">
    <meta itemscope itemprop="mainEntityOfPage" itemType="https://schema.org/WebPage" itemid="<?php echo $post->getPostUrl(); ?>"/>
    <div class="page-title">
        <h1 itemprop="headline"><?php echo $post->getTitle(); ?></h1>
        <h3><?php echo $post->getCreatedTime(); ?></h3>
    </div>
    <meta itemprop="datePublished" content="<?php echo $this->getMicrodataDatePublished($post); ?>"/>
    <meta itemprop="dateModified" content="<?php echo $this->getMicrodataDateModified($post); ?>"/>
    <div style="display:none" itemtype="http://schema.org/Organization" itemscope itemprop="publisher">
        <meta itemprop="name" content="<?php echo $this->getMicrodataPublisherName(); ?>" />
        <div style="display:none" itemtype="http://schema.org/ImageObject" itemscope itemprop="logo">
            <meta itemprop="url" content="<?php echo $this->getMicrodataPublisherLogo(); ?>"/>
        </div>
    </div>

    <?php if ($postImageUrl = $post->getImageUrl()): ?>
        <div class="postImage" itemtype="http://schema.org/ImageObject" itemscope itemprop="image">
            <img src="<?php echo $postImageUrl; ?>" alt="" class="img-responsive" itemprop="url">
            <?php $imageDimensions = $this->getPostImageDimensions($post); ?>
            <meta itemprop="width" content="<?php echo $imageDimensions[0]; ?>"/>
            <meta itemprop="height" content="<?php echo $imageDimensions[1]; ?>"/>
        </div>
    <?php elseif ($postSmallImageUrl = $post->getSmallImageUrl()): ?>
        <div style="display:none" itemtype="http://schema.org/ImageObject" itemscope itemprop="image">
            <meta itemprop="url" content="<?php echo $postSmallImageUrl; ?>"/>
            <?php $imageDimensions = $this->getPostSmallImageDimensions($post); ?>
            <meta itemprop="width" content="<?php echo $imageDimensions[0]; ?>"/>
            <meta itemprop="height" content="<?php echo $imageDimensions[1]; ?>"/>
        </div>
    <?php endif; ?>

    <div class="postContent std" itemprop="articleBody"><?php echo $post->getPostContent(); ?></div>

    <div class="postDetails">
        <?php $postCats = $post->getCategories(); ?>
        <?php if ($postCats->getSize() == 0): ?>
            <?php echo $helper->__("Posted"); ?>
        <?php else: ?>
            <?php echo $helper->__("Posted in"); ?>
            <?php foreach ($postCats as $cat): ?>
                <a href="<?php echo $cat->getCatUrl(); ?>"><?php echo $this->escapeHtml($cat->getTitle()); ?></a>
            <?php endforeach; ?>
        <?php endif; ?> by
        <?php if ($blog->getSettingFlag("authors/enabled")): ?>
        <a href="<?php echo $post->getAuthor()->getAuthorUrl(); ?>" itemprop="author"><?php echo $this->escapeHtml($post->getAuthor()->getName()); ?></a>
        <?php else: ?>
        <span itemprop="author"><?php echo $this->escapeHtml($post->getAuthor()->getName()); ?></span>
        <?php endif; ?>
        <br />
        <?php $postTags = $post->getTags(); ?>
        <?php if ($postTags->getSize() > 0): ?>
            <?php echo $helper->__("Tagged in"); ?>
            <?php foreach ($postTags as $tag): ?>
                <a href="<?php echo $tag->getTagUrl(); ?>"><?php echo $this->escapeHtml($tag->getName()); ?></a>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <?php if ($addthisButtonType = $blog->getSetting("posts/addthis_button_type")): ?>
    <div class="<?php echo $addthisButtonType; ?>"></div>
    <?php endif; ?>
</div>

<?php if ($this->getCommentsEnabled()): ?>
    <div class="postTitle"><a name="commentBox"></a>
        <h2><?php echo $this->getCommentTotalString($post->getCommentCount()); ?></h2>
    </div>

    <?php echo $this->getChild("comments")->setComments($post->getThreadedComments())->toHtml(); ?>

    <?php if ($post->canPostNewComments()): ?>
        <form action="<?php echo $this->getFormAction(); ?>" id="postComment" method="post">
            <fieldset class="group-select">
                <h4 class="legend"><?php echo $helper->__("Submit Comment"); ?></h4>
                <ul>
                    <li id="inReplyToBox" class="no-display">
                        <input name="in_reply_to" id="in_reply_to" type="hidden" value="" />
                        In response to: <span id="inReplyToName"></span>
                    </li>
                    <li>
                        <?php if (!$customerHelper->isLoggedIn()): ?>
                            <div class="input-box">
                                <label for="user"><?php echo $helper->__("Name"); ?> <span class="required">*</span></label><br />
                                <input name="user" id="user" title="<?php echo $this->__("Name"); ?>" class="required-entry input-text" type="text" />
                            </div>
                            <div class="input-box">
                                <label for="email"><?php echo $helper->__("Email"); ?> <span class="required">*</span></label><br />
                                <input name="email" id="email" title="<?php echo $this->__("Email"); ?>" class="required-entry input-text validate-email" type="text" />
                            </div>
                            <div class="clear"></div>
                        <?php endif; ?>
                        <div class="input-box">
                            <label for="comment"><?php echo $helper->__("Comment"); ?> <span class="required">*</span></label><br />
                            <textarea name="comment" id="comment" title="<?php echo $helper->__("Comment"); ?>" class="required-entry input-text" style="height: 150px; width: 400px;" cols="50" rows="5"></textarea>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <?php if ($blog->useRecaptcha()): ?>
                <div><?php echo $this->getChildHtml("recaptcha_box"); ?></div>
            <?php endif; ?>
            <div class="button-set">
                <?php if ($customerHelper->isLoggedIn()): ?>
                    <input name="email" type="hidden" value="<?php echo $this->escapeHtml($helper->getUserEmail()); ?>"/>
                    <input name="user" type="hidden" value="<?php echo $this->escapeHtml($helper->getUserName()); ?>"/>
                <?php endif; ?>
                <p class="required"><?php echo $this->__("* Required Fields"); ?></p>
                <button class="button" type="submit"><span><span><?php echo $helper->__("Submit Comment"); ?></span></span></button>
            </div>
        </form>
        <script type="text/javascript">
            function setupReply(commentID) {
                document.getElementById("inReplyToName").innerHTML = document.getElementById("commentUser_" + commentID).innerHTML;
                document.getElementById("in_reply_to").value = commentID;
                document.getElementById("inReplyToBox").className = "";
            }
        </script>
    <?php else: ?>
        <?php if ($post->getCommentsDisabled()): ?>
            <div class="postError"><?php echo $helper->__("Comments are closed for this post"); ?></div>
        <?php elseif ($this->isLoginRequired() === true && !$customerHelper->isLoggedIn()): ?>
            <p><?php echo $helper->__("You must be logged in to post a comment."); ?></p>
            <p><a href="<?php echo $customerHelper->getLoginUrl(); ?>"><?php echo $helper->__("Click here"); ?></a> <?php echo $helper->__("to log in"); ?></p>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
