<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php /** @var $this Fontis_Blog_Block_Menu */ ?>

<?php if ($archives = $this->getArchives($this->getUseArchiveLimit())): ?>
    <?php $showPostCount = $this->showPostCount(); ?>
    <?php $helper = Mage::helper("blog"); ?>
    <h5><?php echo $helper->__($this->getArchiveLabel() . " Archives"); ?></h5>
    <ul>
    <?php foreach ($archives as $archive): ?>
        <li>
            <a href="<?php echo $archive->getAddress(); ?>"><?php echo $archive->getDateString(); ?></a><?php if ($showPostCount) { echo ' (' . $archive->getPostcount() . ')'; } ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php if ($this->getUseArchiveLimit()): ?>
    <a href="<?php echo $this->getBlog()->getBlogUrl($helper->getBlogArchiveRoute()); ?>"><?php echo $this->__("See All"); ?></a>
    <?php endif; ?>
<?php endif; ?>
