<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php /** @var $this Fontis_Blog_Block_Post_Comment */ ?>

<?php
$blog = $this->getBlog();
$blogHelper = Mage::helper("blog");
$threadedComments = $this->getComments();
$gravEnabled = $this->isGravatarEnabled();
$gravSize = $this->getGravatarSize();
?>

<?php foreach ($threadedComments as $commentId => $value): ?>
    <?php /** @var $comment Fontis_Blog_Model_Comment */ ?>
    <?php $comment = $value["comment"]; ?>
    <div class="commentWrapper" itemscope itemtype="http://schema.org/UserComments">
        <div class="commentContent" itemprop="commentText"><?php echo nl2br($this->escapeHtml($comment->getComment())); ?></div>
        <div class="commentDetails" style="height: <?php echo $gravEnabled ? 15 + $gravSize : 15; ?>px;">
            <?php if ($this->canPostNewComments()): ?>
                <div class="commentReply"><a href="#postComment" onClick="setupReply(<?php echo $commentId; ?>);"><?php echo $blogHelper->__("Reply"); ?></a></div>
            <?php endif; ?>
            <div class="commentPostDetails">
                <?php if ($this->isGravatarEnabled()): ?>
                <div class="commentGravatar">
                    <img src="<?php echo $this->getGravatarUrl($comment->getEmail()); ?>" alt="" width="<?php echo $gravSize; ?>" height="<?php echo $gravSize; ?>" itemprop="image" />
                </div>
                <?php endif; ?>
                <div class="commentUserDetails">
                <?php echo $blogHelper->__("Comment by"); ?> <span id="commentUser_<?php echo $commentId; ?>" itemprop="creator"><?php echo $this->escapeHtml($comment->getUser()); ?></span> - <?php echo $comment->getCreatedTime(); ?>
                <meta itemprop="commentTime" content="<?php echo $this->getMicrodataDatePublished($comment); ?>" />
                </div>
            </div>
        </div>
        <?php if (!empty($value["children"])): ?>
            <div class="commentIndent">
                <?php echo $this->renderChildComments($value["children"]); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
