<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php /** @var $this Fontis_Blog_Block_Form_BlogSwitcher */ ?>

<?php if ($blogs = $this->getBlogs()): ?>
    <p class="switcher"><label for="blog_switcher"><?php echo $this->__("Choose Blog") ?>:</label>
        <select name="blog_switcher" id="blog_switcher" onchange="return switchBlog(this);" style="min-width: 150px;">
            <option value=""><?php echo $this->getDefaultBlogName(); ?></option>
            <?php foreach ($blogs as $blog): ?>
            <option value="<?php echo $blog["value"]; ?>"<?php if ($this->getBlogId() == $blog["value"]): ?> selected="selected"<?php endif; ?>><?php echo $blog["label"]; ?></option>
            <?php endforeach; ?>
        </select>
    </p>
    <script type="text/javascript">
        function switchBlog(obj) {
            var blogParam = obj.value ? "blog/" + obj.value + "/" : "blog/0";
            setLocation('<?php echo $this->getSwitchUrl(); ?>' + blogParam);
        }
    </script>
<?php endif; ?>
